baseurl: "/plugins"
url: "https://ChatSurfApp.github.io"
collections:
    plugins:
        output: true
        permalink: /:name
    categories:
        output: true
        permalink: /categories/:name
