baseurl: "/plugins"
url: "https://ChatSurfApp.github.io"

nav:
    - name: Categories
      url: /plugins/categories
    - name: Developers
      url: /plugins/add

collections:
    plugins:
        output: true
        permalink: /:name
    categories:
        output: true
        permalink: /categories/:name
    developers:
        output: true
        permalink: /developers/:name
